import fs from 'node:fs';
import path from 'node:path';
import type { RecordingPayload, RecordingStatus } from '@orbit/shared';
import { env } from '../../config/env';
import { logger } from '../../lib/logger';
import { describeEgress } from '../../lib/livekit';
import { prisma } from '../../lib/prisma';

/**
 * Meeting recordings.
 *
 * Audio only, and deliberately so: one mixed track of the conversation is what
 * people want afterwards, and producing it costs a fraction of a composite
 * video recording, which needs a headless browser per meeting.
 *
 * Nothing here is served from a static directory. A recording is fetched
 * through an authorised route that checks the caller is a host of *that*
 * meeting, so a leaked or guessed id is not enough — and the files never sit
 * under a path the web server would hand out.
 */

export function toRecordingPayload(
  row: {
    id: string;
    status: string;
    startedAt: Date;
    endedAt: Date | null;
    durationSec: number | null;
    sizeBytes: bigint | null;
    audioOnly: boolean;
    fileName: string | null;
    mimeType: string | null;
  },
  options: { canDownload: boolean; meetingId: string },
): RecordingPayload {
  return {
    id: row.id,
    status: row.status as RecordingStatus,
    startedAt: row.startedAt.toISOString(),
    endedAt: row.endedAt?.toISOString() ?? null,
    durationSec: row.durationSec,
    // BigInt does not survive JSON, and a recording will never be large enough
    // for the precision loss to matter.
    sizeBytes: row.sizeBytes === null ? null : Number(row.sizeBytes),
    audioOnly: row.audioOnly,
    fileName: row.fileName,
    mimeType: row.mimeType,
    downloadUrl:
      options.canDownload && row.status === 'COMPLETED'
        ? `/meetings/${options.meetingId}/recordings/${row.id}/download`
        : null,
  };
}

export async function listRecordings(meetingId: string): Promise<RecordingPayload[]> {
  const rows = await prisma.recording.findMany({
    where: { meetingId },
    orderBy: { startedAt: 'desc' },
  });
  // Only hosts ever reach this, so the download link is always included.
  return rows.map((row) => toRecordingPayload(row, { canDownload: true, meetingId }));
}

/** Resolves the on-disk path for a recording, or null when it is not readable. */
export function recordingFilePath(fileName: string): string | null {
  // The stored name is generated by this server, but it is still resolved and
  // checked against the output directory: a name that escapes the directory
  // must never turn into an arbitrary file read.
  const base = path.resolve(env.RECORDING_OUTPUT_DIR);
  const resolved = path.resolve(base, path.basename(fileName));
  if (!resolved.startsWith(base)) return null;
  return resolved;
}

/**
 * Finishes a recording row once the SFU reports the egress is done.
 *
 * Stopping is a request, not a completion: the file is still being finalised
 * for a moment afterwards. This polls briefly rather than assuming, so the
 * duration and size shown to the host are the real ones.
 */
export async function finaliseRecording(recordingId: string): Promise<void> {
  const recording = await prisma.recording.findUnique({ where: { id: recordingId } });
  if (!recording?.egressId) return;

  for (let attempt = 0; attempt < 15; attempt += 1) {
    const info = await describeEgress(recording.egressId);
    const status = info?.status;

    // 3 = EGRESS_COMPLETE, 4 = EGRESS_FAILED in the LiveKit enum.
    const complete = status === 3;
    const failed = status === 4;

    if (complete || failed) {
      let sizeBytes: bigint | null = null;
      const filePath = recording.fileName ? recordingFilePath(recording.fileName) : null;

      if (filePath) {
        try {
          sizeBytes = BigInt(fs.statSync(filePath).size);
        } catch {
          // Egress writes inside its own container; if the volume is not
          // shared the file is simply not visible here.
          sizeBytes = null;
        }
      }

      const endedAt = new Date();
      await prisma.recording.update({
        where: { id: recordingId },
        data: {
          status: complete && sizeBytes !== null ? 'COMPLETED' : complete ? 'COMPLETED' : 'FAILED',
          endedAt,
          durationSec: Math.max(1, Math.round((endedAt.getTime() - recording.startedAt.getTime()) / 1000)),
          sizeBytes,
          ...(failed ? { error: 'The recording service reported a failure.' } : {}),
        },
      });

      logger.info({ recordingId, status: complete ? 'COMPLETED' : 'FAILED' }, 'recording finalised');
      return;
    }

    await new Promise((resolve) => setTimeout(resolve, 2000));
  }

  // Never resolved: mark it rather than leaving a row stuck on STOPPING.
  await prisma.recording.update({
    where: { id: recordingId },
    data: {
      status: 'FAILED',
      endedAt: new Date(),
      error: 'The recording did not finish in time.',
    },
  });
}

/**
 * Whether this caller may download a given recording.
 *
 * Both the meeting and the role are checked: being a host of one meeting says
 * nothing about another, and that is exactly the mistake a guessed id would
 * try to exploit.
 */
export async function canDownloadRecording(input: {
  recordingId: string;
  meetingId: string;
  userId: string | null;
}): Promise<{ allowed: boolean; fileName: string | null; mimeType: string | null }> {
  if (!input.userId) return { allowed: false, fileName: null, mimeType: null };

  const recording = await prisma.recording.findFirst({
    where: { id: input.recordingId, meetingId: input.meetingId },
    select: { fileName: true, mimeType: true, status: true },
  });
  if (!recording || recording.status !== 'COMPLETED') {
    return { allowed: false, fileName: null, mimeType: null };
  }

  const participant = await prisma.meetingParticipant.findFirst({
    where: { meetingId: input.meetingId, userId: input.userId, role: { in: ['HOST', 'COHOST'] } },
    select: { role: true },
  });

  // The meeting owner counts even if they never joined as a participant row.
  const meeting = await prisma.meeting.findUnique({
    where: { id: input.meetingId },
    select: { hostId: true },
  });

  const allowed = Boolean(participant) || meeting?.hostId === input.userId;

  return {
    allowed,
    fileName: allowed ? recording.fileName : null,
    mimeType: allowed ? recording.mimeType : null,
  };
}
